main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: /#projects
    weight: 20
  - name: Experience
    url: experience/
    weight: 30
  - name: Blog
    url: blog/
    weight: 40
  - name: GitHub
    url: https://github.com/HAMm-CODE
    weight: 50
  - name: LinkedIn
    url: https://www.linkedin.com/in/hamza-sentongo-55483a243/
    weight: 60
